version: '3.8'

services:
  servidor:
    build:
      context: ./servidor
      dockerfile: Dockerfile
    container_name: docker-comps
    ports:
      - "5000:5000" 
    depends_on:
      - ./cliente

  cliente:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    container_name: servicio_cliente


networks:
  red_calculadora:
    driver: bridge

# comando para levantar los servicios: docker-compose up -d